/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libevaluadorjava_EvaluadorJava */

#ifndef _Included_libevaluadorjava_EvaluadorJava
#define _Included_libevaluadorjava_EvaluadorJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libevaluadorjava_EvaluadorJava
 * Method:    evaluar
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libevaluadorjava_EvaluadorJava_evaluar
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
