/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libevaluador_Evaluador */

#ifndef _Included_libevaluador_Evaluador
#define _Included_libevaluador_Evaluador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libevaluador_Evaluador
 * Method:    evaluar
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libevaluador_Evaluador_evaluar__Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     libevaluador_Evaluador
 * Method:    evaluar
 * Signature: (Ljava/lang/String;I[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libevaluador_Evaluador_evaluar__Ljava_lang_String_2I_3B
  (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     libevaluador_Evaluador
 * Method:    cargarProblema
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libevaluador_Evaluador_cargarProblema__Ljava_lang_String_2ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jint, jstring, jstring);

/*
 * Class:     libevaluador_Evaluador
 * Method:    cargarProblema
 * Signature: (Ljava/lang/String;I[B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libevaluador_Evaluador_cargarProblema__Ljava_lang_String_2I_3B_3B
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
