/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libevaluador_Evaluador */

#ifndef _Included_libevaluador_Evaluador
#define _Included_libevaluador_Evaluador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libevaluador_Evaluador
 * Method:    evaluar
 * Signature: (Ljava/lang/String;[[Ljava/lang/String;[[Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libevaluador_Evaluador_evaluar
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
